spring:
  application:
    name: spring-cloud-basic-hystrix-trubine-three
server:
  port: 8086
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
turbine:
  app-config: SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-Three
  cluster-name-expression: spring-cloud-basic-hystrix-trubine-three
  combine-host-port: true
  app-config-list: SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX,SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-Three,SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-PROPAGATION
turbine:
  instanceUrlSuffix:
    SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX: /ribbon/hystrix.stream
logging:
  level:
    root: info
      com.netfix.turbine.monitor: debug