spring:
  application:
    name: spring-cloud-basic-hystrix-trubine-two
server:
  port: 8085
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
turbine:
  app-config: SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-TWO
  cluster-name-expression: "'default'" # ==new String("default")
  combine-host-port: true
  app-config-list: SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX,SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-TWO,SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-PROPAGATION
turbine:
  instanceUrlSuffix:
    SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX: /ribbon/hystrix.stream
logging:
  level:
    root: info
      com.netfix.turbine.monitor: debug