security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8762/eureka
  dashboard:
    path: /admin
    enabled: true
spring:
  application:
    name: erueka-ha
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1 #域名
  client:
    serviceUrl:
      defaultZone: http://peer2/eureka/
server:
  port: 8761

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2 #域名
  client:
    serviceUrl:
      defaultZone: http://peer1/eureka/
---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
