spring:
  application:
    name: spring-cloud-basic-hystrix-trubine
server:
  port: 8084
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
turbine:
  app-config: SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX
  cluster-name-expression: "'default'" # ==new String("default")
  combine-host-port: true
  app-config-list: SPRING-CLOUD-BASIC-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX,spring-cloud-basic-consumer-movie-ribbon-with-hystrix-propagation
