#用户名密码
server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smalllc/spring-cloud-learning
          username:
          password:
encrypt:
  key: foo