spring:
  application:
    name: spring-cloud-basic-consumer-movie-ribbon-customizing
server:
  port: 8011
user: 
  userServicePath: http://localhost:7900/simple/
eureka:
  client:
    region:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring-cloud-basic-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule #使用随机方式  默认是轮询

