#用户名密码
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smalllc/simple
          username:
          password:
  application:
    name: spring-cloud-basic-config-server-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
