security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8041
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    ip-address: ture
spring:
  application:
    name: spring-cloud-basic-gateway-zuul-reg-exp
zuul:
  prefix: /api
  strip-prefix: false  # 剥掉前缀 就是不使用前缀 这里的前缀是serverId
logging:
  level:
    com.netfix: debug
