security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    ip-address: ture
spring:
  application:
    name: spring-cloud-basic-sidecar
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health

